name: "Create GitHub Release"
description: "Create a GitHub Release and optionally upload files"
inputs:
  tag_name:
    description: "Release tag name (e.g., v1.0.0)"
    required: true
  release_name:
    description: "Display name of the release"
    required: false
    default: ""
  body:
    description: "Release notes/description"
    required: false
    default: ""
  files:
    description: "Optional files or directories to upload"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag_name }}
        name: ${{ inputs.release_name }}
        body: ${{ inputs.body }}
        files: ${{ inputs.files }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
