name: "Lint and Test"
description: "Run linting and tests for a Node.js/React project"

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "20"

runs:
  using: "composite"
  steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Run lint
      run: npm run lint --if-present
      shell: bash

    - name: Run tests
      run: npm test --if-present -- --ci --coverage
      shell: bash
