name: Check for Missing Django Migrations
description: Run Django makemigrations --check
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - run: |
        python -m pip install --upgrade pip
        pip install -e ".[test,dev]"
      shell: bash

    - run: python develop/manage.py makemigrations --check --dry-run
      shell: bash
