name: Check for Missing Django Migrations
description: Run Django makemigrations --check

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - run: |
        python -m pip install --upgrade pip
        pip install -e ".[test,dev]"
      shell: bash

    - run: python develop/manage.py makemigrations --check --dry-run
      shell: bash
