name: 'Build Python Package and Create GitHub Release'
description: 'Build wheel + sdist, create GitHub Release, attach artifacts'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
