name: "Deploy to S3"
description: "Download a build artifact and deploy to S3"
inputs:
  artifact-name:
    description: "Name of the artifact to deploy"
    required: true
  bucket:
    description: "S3 bucket name"
    required: true
  subfolder:
    description: "Path inside the bucket"
    required: true
  aws-region:
    description: "AWS region"
    required: false
    default: "us-east-1"

runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: build/

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}

    - name: Sync to S3
      run: |
        aws s3 sync build/ s3://${{ inputs.bucket }}/${{ inputs.subfolder }}/ --delete
      shell: bash
